import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local" 
import "./globals.css";

const chiru = localFont({
  src:"../public/fonts/chirufont.ttf",
  //variable:"--font-chiru",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={chiru.className}>
      <body
        className={` w-screen h-screen px-2 pt-42 pb-6 inline-flex flex-col justify-start-items-center gap-12 overflow-hidden antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
