import type { Metadata } from "next";
import { Yusei_Magic} from "next/font/google";
import localFont from "next/font/local" 
import "./globals.css";

const chiru = localFont({
  src:"../public/fonts/chirufont.ttf",
})

const yuseiMagic = Yusei_Magic({
  subsets: ['latin', 'japanese'],
  weight:['400']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={yuseiMagic.className}>
      <body
        className="
          w-screen h-screen 
          px-2 pt-42 pb-6 
          inline-flex flex-col justify-start-items-center 
          gap-12
          text-blue-700
          overflow-hidden 
          antialiased"
      >
        {children}
      </body>
    </html>
  );
}
